[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinkerforge = "2.0.20"
clap = {version = "4.1.*", features = ["unstable-doc"]}